---
- name: Check the requirements
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bridge-utils
    - hostapd
  register: installed_packages
  notify: Notify updates of the wireless access point via Slack

- name: Set configurations for br0
  when: installed_packages is succeeded
  become: true
  blockinfile:
    dest: /etc/network/interfaces
    state: present
    block: |
      auto br0
      iface br0 inet dhcp
      bridge_ports eth0 wlan0
  notify: Notify updates of the wireless access point via Slack

- name: Put /etc/hostapd/hostapd.conf
  when: installed_packages is succeeded
  become: true
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
  notify: Notify updates of the wireless access point via Slack

- name: Set DAEMON_CONF at /etc/default/hostapd
  when: installed_packages is succeeded
  become: true
  replace:
    path: /etc/default/hostapd
    regexp: '^#DAEMON_CONF=.*$'
    replace: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: Notify updates of the wireless access point via Slack

- name: Make br0 up
  when: installed_packages is succeeded
  become: true
  net_interface:
    name: br0
    state: up
    enabled: True
  notify: Notify updates of the wireless access point via Slack

- name: Start and enable hostapd
  when: installed_packages is succeeded
  become: true
  systemd:
    name: hostapd
    state: started
    daemon_reload: yes
    enabled: true
  notify: Notify updates of the wireless access point via Slack
